name: Hotel IPTV Reborn AutoTask

on:
  schedule:
    - cron: '0 17 * * *' # 每天北京时间凌晨1点运行
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install requests tqdm

      - name: Step 1 - Scan New IPs
        run: python py/scan_hotel.py

      - name: Step 2 - Rebuild M3U Lists
        run: python py/rebuild_m3u.py

      - name: Step 3 - Commit and Push
        run: |
          git config --global user.name "HotelRebornBot"
          git config --global user.email "bot@iptv.com"
          git add reborn_list/ py/scan_map.json
          git commit -m "Update Reborn Sources: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push
